version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: cibuilds/hugo:latest
    steps:
      - checkout
      - run:
          name: Yarn Configuration
          command: curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add - && echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
      - run:
          name: Install Yarn
          command: sudo apt-get update && sudo apt-get install yarn
      - run:
          name: Install Firebase Tools
          command: yarn add firebase-tools --dev
      - run:
          name: Build
          command: hugo -t hugo-icarus-theme
      - run:
          name: Deploy
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN
