version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: seitauc/docker-hugo-firebase:latest
    steps:
      - checkout
      - run:
          name: Build Hugo Website
          command: hugo -t hugo-icarus-theme
      - run:
          name: cd 
          command: cd ./public && ls
      - deploy:
          name: Deploy Website to Firebase Hosting
          branch: master
          command: firebase deploy --token=$FIREBASE_DEPLOY_TOKEN --project seita-blog
