version: 2
jobs:
  build:
    branches:
      only:
        - master
    working_directory: ~/repo
    docker:
      - image: cibuilds/hugo:latest
    steps:
      - checkout
      - run:
          name: Install Firebase Tools
          command: npm install --save-dev firebase-tools
      - run:
          name: Build
          command: hugo -t hugo-icarus-theme
      - run:
          name: Deploy
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN
