version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: seitauc/docker-hugo-firebase:latest
    steps:
      - checkout
      - run:
          name: Build
          command: hugo -t hugo-icarus-theme
      - run:
          name: Deploy
          command: firebase deploy --token=$FIREBASE_DEPLOY_TOKEN
